# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 328552d87219f99ba39ddfc83e8acb2f432ad93d913921f5f266cb736a04d66fc19813d8f03dff97b5edd69e769206a197cbff43411127828ec8ca30f082e979

test:
  secret_key_base: 1e9b51a12da253d24731927666f6bc40e0d6b913b3b1d0fe856c6295a3027b8c8a1d636ed38746bf1fafd26d4fb39d4f2294d2af5bb21da2c485ed86af82d50b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
